---
title: "draft"
author: "Hanmeng Xu"
date: "2024-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Age eligibility
```{r}
temp <- df %>% filter(DOB < as.Date("2023-2-1")) # there are 1049 born before 2023-2-1

#check if they are high risk infants
temp <- temp %>% filter(
                  is.na(risk_factor_preterm) &
                  is.na(risk_factor_cvd) &
                  is.na(risk_factor_anemia) &
                  is.na(risk_factor_pulmonary) &
                  is.na(risk_factor_congen_heart) &
                  is.na(risk_factor_asthma) &
                  is.na(risk_factor_gi) &
                  is.na(risk_factor_down) &
                  is.na(risk_factor_liver) &
                  is.na(risk_factor_blood) &
                  is.na(risk_factor_cardiac) &
                  is.na(risk_factor_immunodeficiency) &
                    risk_factor_gestage != "preterm") # detected 576 infants


# select important columns 
output <- temp %>% 
  select(StudyID, collection_date, DOB, admit_date, date_icu_admit, `Collection Department`, `Encounter Type`, positive_rsv,  rsv_mab, 
         `Medical History`, `Problem List`, `Primary Problem`, `ED Dx`, `Admit Dx`, `Hospital Problem List`,
         risk_factor_preterm,
         risk_factor_anemia,
         risk_factor_pulmonary, 
         risk_factor_cardiac,
         risk_factor_asthma, 
         risk_factor_gi,
         risk_factor_down, 
         risk_factor_liver,
         risk_factor_immunodeficiency)

write.csv(output, "../../data/need help/uncertain_high_risk.csv", row.names = F,na = "")



temp %>% count(positive_rsv) # 213 cases (RSV+)
temp %>% count(case_control)
temp %>% count(encounter_type)
temp %>% count(rsv_mab)

(temp %>% filter(rsv_mab == 1))$StudyID

table(temp$case_control, temp$encounter_type)
table(temp$positive_rsv, temp$encounter_type)

# even for high risk infants, mab should be given to those under 19 months (CDC), thus those born before 2022.3.1 are older than 19 months on 2024.10.1, thus not eligible for mAb. Check how many:
temp %>% filter(DOB < as.Date("2022-3-1")) # 0, thus all are under 19 month when mAb was available.

```

Admit date
```{r}
# check how many records have collection date more than 7 days after admission.
temp <- df %>% filter(days_btw_admit_collect > 7)

a <- temp %>% filter(DOB != as.Date(`Admit Date`) | DOB != date_icu_admit)

temp %>% count(positive_rsv)
temp %>% count(rsv_mab)

# there is one rsv+ case, need help checking if this one should be counted as a "related ICU"
a <- temp %>% filter(positive_rsv == 1)

write.csv(a, "../../data/need help/confirm_admission_reason.csv", row.names = F, na = "")
```

ICU admission date
```{r}
temp <- df %>% filter(days_btw_collection_icu > 7) %>%
  mutate(type = ifelse(DOB == admit_date & DOB == date_icu_admit, 
                       "ICU admission on DOB", NA))

```


Gestational age (many missing)
```{r}
a <- df %>% filter(is.na(risk_factor_gestage)) 
```

Birth weight (if assuming unit is ounce)
```{r}
a <- df %>% mutate(birth_weight = as.numeric(`Birth Wgt`) * 28.3)

a %>% filter(birth_weight < 2500) %>% count(gest_age_cat)

df %>% filter(is.na(`Birth Wgt`))
```

Race
```{r}
unique(df$Race)
df %>% filter(Race == "White\r\nBlack or African American")
```
Insurance type 
```{r}
df %>% filter(is.na(`Primary Insurance`))
df %>% filter(is.na(`Payor`))
df %>% filter(is.na(`Primary Insurance`) & is.na(Payor))

df %>% filter(`Primary Insurance` == "LOCAL 1199SEIU BENEFIT FUNDS")

df %>% filter(`Primary Insurance` != Payor)

unique(df$`Primary Insurance`)

df %>% filter(str_detect(`Primary Insurance`, "MCD MGD") | str_detect(Payor, "MCD MGD"))
```


detect Risk factors 
```{r}
(df %>% filter(grepl("cardiac",`Medical History`,  ignore.case = T)) %>% select(`Medical History`))$`Medical History`
(df %>% filter(grepl("cardiac",`Problem List`,  ignore.case = T)) %>% select(`Problem List`))$`Problem List`
(df %>% filter(grepl("cardiac",`Primary Problem`,  ignore.case = T)) %>% select(`Primary Problem`))$`Primary Problem`
(df %>% filter(grepl("cardiac",`ED Dx`,  ignore.case = T)) %>% select(`ED Dx`))$`ED Dx`
(df %>% filter(grepl("cardiac",`Hospital Problem List`,  ignore.case = T)) %>% select(`Hospital Problem List`))$`Hospital Problem List`

```


Max flow rate 
```{r}
df %>% filter(max_oxygen_flowrate > 1.5)
```


whether this individual is suspected respiratory infection?
```{r}
# patients that I can't detect any respiratory disease patterns
temp  <- df %>% filter(is.na(symp_URT_distress) & is.na(symp_LRT_distress) & is.na(symp_fever) & is.na(symp_cough) & is.na(symp_wheezing) & is.na(symp_breathing) & is.na(symp_bronchiolitis) & is.na(symp_sepsis) &
                     grepl(pattern_suspect_resp_general, `Primary Problem`,ignore.case = T) %in% c(NA, FALSE)  & 
                     grepl(pattern_suspect_resp_general, `ED Dx`, ignore.case = T) %in% c(NA, FALSE) & 
                     grepl(pattern_suspect_resp_general, `Admit Dx`,ignore.case = T) %in% c(NA, FALSE) & 
                     grepl(pattern_suspect_resp_general, `Hospital Problem List`,ignore.case = T) %in% c(NA, FALSE)                   )



a <- temp %>% 
  select(StudyID, collection_date, DOB, admit_date, date_icu_admit, `Collection Department`, `Encounter Type`, positive_rsv,  rsv_mab, 
           `ED Dx`, `Admit Dx`,  # main variables to use
         `Medical History`, `Problem List`, `Primary Problem`,`Hospital Problem List`) %>% 
  mutate(is_suspected_resp = NA)


write.csv(a, "../../data/need help/uncertain_suspected_respiratory.csv", row.names = F, na="")
```


# Bernstein polynomials approximation
```{r}
# Load necessary library
if (!requireNamespace("polynom", quietly = TRUE)) {
  install.packages("polynom")
}
library(polynom)

# Function to calculate Bernstein basis polynomial
bernstein_basis <- function(n, k, t) {
  choose(n, k) * (t^k) * ((1 - t)^(n - k))
}

# Function to generate Bernstein polynomial approximation for f(t) = 1/t
bernstein_approximation <- function(n, t) {
  approximation <- numeric(length(t))
  for (k in 0:n) {
    f_k <- 1 / (k / n) # Evaluate f at k/n for f(t) = 1/t
    basis <- bernstein_basis(n, k, t)
    approximation <- approximation + f_k * basis
  }
  return(approximation)
}

# Normalize a continuous variable to the range [0, 1]
normalize <- function(t) {
  (t - min(t)) / (max(t) - min(t))
}

# Example usage
continuous_variable <- seq(0.01, 1, length.out = 100) # Define the variable t in the interval (0, 1]
n <- 5 # Define the degree of Bernstein polynomials

bernstein_approx <- bernstein_approximation(n, continuous_variable)

# Plot the Bernstein polynomial approximation
plot(continuous_variable, 1 / continuous_variable, type = "l", col = "red", lwd = 2,
     xlab = "t", ylab = "f(t)", ylim = c(0, max(1 / continuous_variable)), main = "Bernstein Approximation of 1/t")
lines(continuous_variable, bernstein_approx, col = "blue", lwd = 2)
legend("topright", legend = c("1/t", paste0("Bernstein Approximation (n=", n, ")")), col = c("red", "blue"), lty = 1)

```


# prepare the data for Nate for genetic data
```{r}
# read in data from onedrive shared folder 
df <- read_excel("../../data/data_to_check/RSV_MPI.xlsx", sheet = "Sheet1") %>% 
  mutate(StudyID = as.character(StudyID))

# read in data of nirsevimab
df.nir <- read_excel("/Users/hmx/OneDrive - Yale University/Hanmeng RSV VE/data/RSV_deid_2024_may.xlsx", sheet = "nirsevimab") %>% mutate(StudyID = as.character(StudyID))

# merge nirsevimab tab with main tab 
df <- df  %>% 
  left_join(df.nir %>% dplyr::select(-`IMM Entry Date`), by = "StudyID")


# mark those vaccinated before sample collection
df <- df %>%
  mutate(vax_before_testing = ifelse(`mAb date` < `Collection Date`, 1, 0)) %>%
  mutate(`mAb date` = as.Date(`mAb date`),
         `Collection Date` = as.Date(`Collection Date`))

write_xlsx(df, path = "../../data/data_to_check/RSV_MPI_a.xlsx")
```














